/*
* 请求数据的所有类型
*/
// 首页数据加载
export const REQUEST_HOME_LIST = 'REQUEST_HOME_LIST'
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST'
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST'
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST'
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST'
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST'

// 学习版块加载类型
export const REQUEST_LEARN_LIST = 'REQUEST_LEARN_LIST'
export const FETCH_LEARN_LIST = 'FETCH_LEARN_LIST'
export const RECEIVE_LEARN_LIST = 'RECEIVE_LEARN_LIST'
// export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST'
// export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST'
// export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST'